"""Wave 51 dim L — Pydantic models for state token + saved_context.

The two models below are the **canonical wire shape** for a dim L
session row. Persistence (``SessionRegistry``) serialises and reloads
each ``SavedContext`` via the Pydantic round-trip so the JSON file on
disk is the source of truth even after a process restart.

Why Pydantic (not a dataclass)?
-------------------------------
* dim L sits on the agent boundary — the contract layer at
  ``src/jpintel_mcp/agent_runtime/contracts.py`` is Pydantic, and
  every dim K-S sibling module (anonymized_query / explainable_fact /
  composable_tools) standardised on Pydantic v2 in Wave 50 (see
  ``docs/_internal/WAVE51_PHASE2_COMPLETE.md``).
* Pydantic validation of ``token_id`` (32 hex chars) + ``expires_at``
  (positive float) catches malformed disk rows on load without a
  separate validator pass.
* ``model_dump`` / ``model_validate`` give us a stable JSON shape for
  the on-disk file without hand-rolled serialisation.

NO HTTP / NO LLM imports — these models are pure data carriers.
"""

from __future__ import annotations

import re
import time
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator

# 24-hour TTL — matches the existing in-process REST surface at
# ``src/jpintel_mcp/api/session_context.py`` so both implementations
# share one TTL contract. NEVER lower without a code-review PR.
SESSION_TTL_SEC: int = 24 * 60 * 60

# Cap a single ``saved_context`` (and each step payload) at 16 KiB. The
# dim L design memo (``feedback_session_context_design``) calls out that
# the surface is **conversation glue**, not durable state. A loud cap is
# the only way to prevent agents from drifting into using the registry
# as a poor-man's database.
MAX_CONTEXT_BYTES: int = 16 * 1024

# Cap the number of step entries per session at 32. The REST surface
# uses the same constant; we mirror it here so a file-backed session
# cannot accept more steps than the in-process counterpart.
MAX_STEPS: int = 32

# Token format: 32 lowercase hex chars (16 bytes). Matches
# ``secrets.token_hex(16)`` output and the existing REST surface so a
# token issued by either implementation looks identical on the wire.
_TOKEN_RE: re.Pattern[str] = re.compile(r"^[0-9a-f]{32}$")


class SessionToken(BaseModel):
    """A 24h-TTL state token.

    Attributes
    ----------
    token_id:
        32 lowercase hex chars (16 random bytes). Generated by
        :func:`jpintel_mcp.session_context.registry.new_token_id`.
    subject_id:
        Caller-supplied opaque identifier (e.g. API key id, agent run
        id). NOT validated for shape — the registry is agnostic about
        whose token this is. NEVER contains PII per dim N redact rules
        (the caller is responsible for normalising upstream).
    created_at:
        Unix epoch seconds at token creation.
    expires_at:
        Unix epoch seconds when this token becomes invalid. Always
        ``created_at + SESSION_TTL_SEC`` at issue time. The registry
        re-checks at every access so an out-of-band clock skew cannot
        silently extend lifetime.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    token_id: str = Field(
        ...,
        min_length=32,
        max_length=32,
        description="32 lowercase hex chars — secrets.token_hex(16) output.",
    )
    subject_id: str = Field(
        ...,
        min_length=1,
        max_length=128,
        description="Caller-supplied opaque id. NOT PII.",
    )
    created_at: float = Field(
        ...,
        gt=0,
        description="Unix epoch seconds at issue time.",
    )
    expires_at: float = Field(
        ...,
        gt=0,
        description="Unix epoch seconds when token becomes invalid.",
    )

    @field_validator("token_id")
    @classmethod
    def _token_must_be_hex32(cls, v: str) -> str:
        if not _TOKEN_RE.match(v):
            raise ValueError(
                "token_id must be 32 lowercase hex chars; produce via "
                "secrets.token_hex(16) (see registry.new_token_id).",
            )
        return v

    def is_expired(self, *, now: float | None = None) -> bool:
        """Return ``True`` when this token's lifetime has lapsed.

        The optional ``now`` argument lets tests deterministically force
        expiry without ``time.sleep``; production callers leave it
        unset and accept ``time.time()`` as the wall-clock source.
        """
        t = time.time() if now is None else now
        return self.expires_at < t


class SavedContext(BaseModel):
    """Persistent state for one open dim L session.

    Attributes
    ----------
    token_id:
        Matches :class:`SessionToken.token_id`. Used as the file name
        on disk (``<token_id>.json``) so a one-pass directory listing
        cleanly enumerates all live sessions.
    subject_id:
        Mirrored from :class:`SessionToken` for audit convenience — a
        post-hoc reader does not need to cross-join two files to see
        whose session expired.
    created_at:
        Mirrored from :class:`SessionToken`. Helps spot stale rows.
    expires_at:
        Mirrored from :class:`SessionToken`. The registry trusts the
        on-disk ``expires_at`` over any caller-supplied "freshen" so a
        compromised client cannot extend its own TTL by re-writing the
        file.
    current_state:
        Free dict for the agent's running intent (filters, last query,
        next_calls scaffold). Capped at :data:`MAX_CONTEXT_BYTES`.
    step_history:
        Append-only list of per-step payloads. Each entry is a dict
        ``{"at": <unix-ts>, "action": <str>, "data": <dict>}``.
        Capped at :data:`MAX_STEPS`.
    """

    model_config = ConfigDict(extra="forbid")

    token_id: str = Field(..., min_length=32, max_length=32)
    subject_id: str = Field(..., min_length=1, max_length=128)
    created_at: float = Field(..., gt=0)
    expires_at: float = Field(..., gt=0)
    current_state: dict[str, Any] = Field(default_factory=dict)
    step_history: list[dict[str, Any]] = Field(default_factory=list)

    @field_validator("token_id")
    @classmethod
    def _token_must_be_hex32(cls, v: str) -> str:
        if not _TOKEN_RE.match(v):
            raise ValueError(
                "token_id must be 32 lowercase hex chars (matches "
                "SessionToken format).",
            )
        return v

    def is_expired(self, *, now: float | None = None) -> bool:
        """Return ``True`` when the underlying token has lapsed."""
        t = time.time() if now is None else now
        return self.expires_at < t

    def steps_count(self) -> int:
        """Return the number of recorded steps so far."""
        return len(self.step_history)


__all__ = [
    "MAX_CONTEXT_BYTES",
    "MAX_STEPS",
    "SESSION_TTL_SEC",
    "SavedContext",
    "SessionToken",
]
