-- target_db: autonomath
-- migration: 262_fact_signature_v2_rollback
-- DOWN companion to 262_fact_signature_v2.sql
--
-- Drops the per-fact Ed25519 signature table + indexes + latest view.
-- Reversible: re-applying 262_fact_signature_v2.sql restores the schema
-- (signatures themselves must be re-generated by the weekly cron).

PRAGMA foreign_keys = ON;

BEGIN;

DROP VIEW IF EXISTS v_am_fact_signature_latest;
DROP INDEX IF EXISTS idx_am_fact_signature_keyid;
DROP INDEX IF EXISTS idx_am_fact_signature_snapshot;
DROP INDEX IF EXISTS idx_am_fact_signature_lookup;
DROP TABLE IF EXISTS am_fact_signature;

COMMIT;
