-- target_db: autonomath
-- ROLLBACK companion for wave24_110_am_entities_vec_v2.sql
-- Excluded from entrypoint.sh §4 by the `*_rollback.sql` name fence.
--
-- Manual review required before running. Order matters: drop the
-- vec0 virtual table FIRST (which also drops vec0's external
-- chunk tables — am_entities_vec_v2_chunks / _info / _rowids /
-- _vector_chunks00), then the metadata sidecar.
--
-- Re-creation is via this migration's UP file; embeddings must be
-- regenerated by `scripts/etl/rebuild_am_entities_vec_v2.py`.

PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS am_entities_vec_v2;
DROP TABLE IF EXISTS am_entities_vec_v2_metadata;

PRAGMA foreign_keys = ON;
