#!/usr/bin/env python3
"""Generate JPCIR schema reference markdown from schemas/jpcir/*.schema.json.

Reads every JSON Schema file under ``schemas/jpcir/`` and emits a single
markdown reference at ``docs/_internal/JPCIR_SCHEMA_REFERENCE.md``.

Wave 50 RC1: ships alongside the 20 schema landing + Pydantic
round-trip checker (``scripts/check_schema_contract_parity.py``).

Pure stdlib — no third-party deps. Idempotent regeneration is safe; the
output file is overwritten in full each run.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_DIR = REPO_ROOT / "schemas" / "jpcir"
OUTPUT_PATH = REPO_ROOT / "docs" / "_internal" / "JPCIR_SCHEMA_REFERENCE.md"


def _format_type(node: dict[str, Any]) -> str:
    """Render a JSON Schema type hint as a short markdown-safe string."""
    if "enum" in node:
        values = ", ".join(f"`{v}`" for v in node["enum"])
        return f"enum({values})"
    if "const" in node:
        return f"const(`{node['const']}`)"
    t = node.get("type")
    if t == "array":
        items = node.get("items") or {}
        inner = _format_type(items) if isinstance(items, dict) else "any"
        return f"array<{inner}>"
    if t == "object":
        return "object"
    if isinstance(t, list):
        return " | ".join(t)
    return str(t or "any")


def _properties_table(schema: dict[str, Any]) -> str:
    """Render properties as a markdown table."""
    properties = schema.get("properties") or {}
    if not properties:
        return "_(no properties)_\n"

    required = set(schema.get("required") or [])
    lines = [
        "| name | type | required | description |",
        "| --- | --- | --- | --- |",
    ]
    for name in sorted(properties):
        prop = properties[name] or {}
        type_str = _format_type(prop)
        req = "yes" if name in required else "no"
        desc_parts: list[str] = []
        if "description" in prop:
            desc_parts.append(str(prop["description"]))
        if "title" in prop and prop["title"] != name:
            desc_parts.append(f"title: {prop['title']}")
        if "minLength" in prop:
            desc_parts.append(f"minLength={prop['minLength']}")
        if "minItems" in prop:
            desc_parts.append(f"minItems={prop['minItems']}")
        if "default" in prop:
            desc_parts.append(f"default=`{prop['default']}`")
        description = "; ".join(desc_parts) if desc_parts else ""
        # markdown-escape pipe chars within description
        description = description.replace("|", "\\|")
        lines.append(f"| `{name}` | {type_str} | {req} | {description} |")
    lines.append("")
    return "\n".join(lines)


def _examples_block(schema: dict[str, Any]) -> str:
    examples = schema.get("examples")
    if not examples:
        return ""
    out_lines = ["", "**Examples:**", ""]
    for example in examples:
        out_lines.append("```json")
        out_lines.append(json.dumps(example, indent=2, ensure_ascii=False))
        out_lines.append("```")
        out_lines.append("")
    return "\n".join(out_lines)


def _render_schema(name: str, schema: dict[str, Any]) -> str:
    title = schema.get("title") or name
    description = schema.get("description") or ""
    schema_id = schema.get("$id", "")

    sections = [f"## {title}", ""]
    sections.append(f"- **file**: `schemas/jpcir/{name}.schema.json`")
    if schema_id:
        sections.append(f"- **$id**: `{schema_id}`")
    schema_version = schema.get("$schema")
    if schema_version:
        sections.append(f"- **$schema**: `{schema_version}`")
    additional = schema.get("additionalProperties")
    if additional is False:
        sections.append("- **additionalProperties**: forbidden")
    elif additional is True:
        sections.append("- **additionalProperties**: allowed")
    sections.append("")

    if description:
        sections.append(description)
        sections.append("")

    sections.append("### Properties")
    sections.append("")
    sections.append(_properties_table(schema))

    examples_md = _examples_block(schema)
    if examples_md:
        sections.append(examples_md)

    return "\n".join(sections)


def discover_schemas() -> list[Path]:
    return sorted(SCHEMA_DIR.glob("*.schema.json"))


def generate() -> str:
    schema_paths = discover_schemas()
    if not schema_paths:
        raise SystemExit(f"no schemas found under {SCHEMA_DIR}")

    now = datetime.now(UTC).isoformat(timespec="seconds")
    header = [
        "# JPCIR Schema Reference",
        "",
        "Auto-generated by `scripts/ops/generate_schema_docs.py`.",
        "Do NOT edit by hand — regenerate with `make schema-docs`.",
        "",
        f"- generated_at: {now}",
        f"- schema_count: {len(schema_paths)}",
        "- source_dir: `schemas/jpcir/`",
        "",
        "## Index",
        "",
    ]
    index_lines: list[str] = []
    body_sections: list[str] = []

    for path in schema_paths:
        name = path.name.removesuffix(".schema.json")
        with path.open("r", encoding="utf-8") as fh:
            schema = json.load(fh)
        title = schema.get("title") or name
        anchor = title.lower().replace(" ", "-").replace("_", "-")
        index_lines.append(f"- [{title}](#{anchor}) — `{name}`")
        body_sections.append(_render_schema(name, schema))

    parts = header + index_lines + ["", "---", ""] + body_sections
    return "\n".join(parts) + "\n"


def main() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    content = generate()
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    line_count = content.count("\n")
    schema_count = len(discover_schemas())
    print(f"generated {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    print(f"  schemas: {schema_count}")
    print(f"  lines: {line_count}")


if __name__ == "__main__":
    main()
