"""Precomputed intelligence REST surface.

This router is intentionally thin: it exposes the compact, precomputed
Evidence Packet path used by the offline token-cost benchmark without
adding an LLM dependency or a second datastore.
"""
from __future__ import annotations

import time
from typing import Annotated, Any, Literal

from fastapi import APIRouter, Query
from fastapi.responses import JSONResponse, Response

from jpintel_mcp.api._audit_seal import attach_seal_to_body
from jpintel_mcp.api.deps import ApiContextDep, DbDep, log_usage
from jpintel_mcp.api.evidence import _get_composer
from jpintel_mcp.services.evidence_packet import MAX_RECORDS_PER_PACKET

router = APIRouter(prefix="/v1/intelligence", tags=["intelligence"])


def _annotate_precomputed_bundle(envelope: dict[str, Any]) -> dict[str, Any]:
    """Add benchmark-facing metadata to an Evidence Packet envelope."""
    records = envelope.get("records") or []
    precomputed_count = sum(1 for rec in records if rec.get("precomputed"))
    gaps = envelope.setdefault("quality", {}).setdefault("known_gaps", [])
    if (
        precomputed_count == 0
        and isinstance(gaps, list)
        and "precomputed_summary_unavailable" not in gaps
    ):
        gaps.append("precomputed_summary_unavailable")

    packet_id = str(envelope.get("packet_id") or "")
    bundle_id = packet_id.replace("evp_", "pci_", 1) if packet_id else ""
    envelope.update(
        {
            "bundle_kind": "precomputed_intelligence",
            "bundle_id": bundle_id,
            "answer_basis": (
                "precomputed" if precomputed_count else "metadata_only"
            ),
            "precomputed": {
                "available": precomputed_count > 0,
                "basis_tables": ["am_program_summary"],
                "record_count": precomputed_count,
                "note": (
                    "Precomputed summaries are deterministic corpus artifacts. "
                    "They are not generated by a request-time LLM."
                ),
            },
            "usage": {
                "intended_for": "llm_context_prefetch",
                "web_search_required": False,
                "jpcite_requests": 1,
                "billing_units": 1,
            },
        }
    )
    return envelope


@router.get(
    "/precomputed/query",
    summary="Precomputed Intelligence Bundle — query prefetch",
    description=(
        "Returns a compact precomputed intelligence bundle for a query. "
        "No LLM call, no live web search. Used by the offline benchmark "
        "arm `jpcite_precomputed_intelligence`."
    ),
)
def get_precomputed_intelligence_query(
    q: Annotated[
        str,
        Query(
            min_length=1,
            max_length=500,
            description="Free-text query to resolve against precomputed program summaries.",
        ),
    ],
    conn: DbDep,
    ctx: ApiContextDep,
    prefecture: Annotated[
        str | None,
        Query(description="Optional prefecture filter."),
    ] = None,
    tier: Annotated[
        str | None,
        Query(description="Optional tier filter."),
    ] = None,
    limit: Annotated[
        int,
        Query(
            ge=1,
            le=MAX_RECORDS_PER_PACKET,
            description=(
                f"Cap on records[] length. Hard cap = {MAX_RECORDS_PER_PACKET}."
            ),
        ),
    ] = 10,
    include_facts: Annotated[
        bool,
        Query(
            description=(
                "Include raw facts in addition to precomputed summaries. "
                "Default false keeps the bundle compact for LLM context."
            ),
        ),
    ] = False,
    include_compression: Annotated[
        bool,
        Query(description="Include deterministic token-compression estimate."),
    ] = True,
    input_token_price_jpy_per_1m: Annotated[
        float | None,
        Query(
            description=(
                "Optional caller input-token price in JPY per 1M tokens. "
                "Used only when an honest savings estimate is possible."
            ),
        ),
    ] = None,
    output_format: Annotated[
        Literal["json"],
        Query(description="Only `json` is supported for benchmark bundles."),
    ] = "json",
) -> Response:
    _t0 = time.perf_counter()
    filters: dict[str, Any] = {}
    if prefecture:
        filters["prefecture"] = prefecture
    if tier:
        filters["tier"] = tier

    composer = _get_composer()
    envelope = composer.compose_for_query(
        q,
        filters,
        limit=limit,
        include_facts=include_facts,
        include_rules=False,
        include_compression=include_compression,
        fields="default",
        input_token_price_jpy_per_1m=input_token_price_jpy_per_1m,
    )
    envelope = _annotate_precomputed_bundle(envelope)

    latency_ms = int((time.perf_counter() - _t0) * 1000)
    log_usage(
        conn,
        ctx,
        "intelligence.precomputed.query",
        latency_ms=latency_ms,
        result_count=len(envelope.get("records") or []),
        params={
            "q": q,
            "limit": limit,
            "filter_keys": sorted(filters),
        },
    )
    attach_seal_to_body(
        envelope,
        endpoint="intelligence.precomputed.query",
        request_params={
            "q": q,
            "limit": limit,
            "filter_keys": sorted(filters),
        },
        api_key_hash=ctx.key_hash,
        conn=conn,
    )
    return JSONResponse(content=envelope)


__all__ = ["router"]
