#!/usr/bin/env python3
"""Build-time consistency check for the published MCP tool count.

Customers fact-check the tool count across the marketing site, llms.txt
files, README, and manifests. If any of those drift from the actual
public distribution manifest, customers see inconsistent numbers and lose
trust.

This script treats ``scripts/distribution_manifest.yml`` as the public
source of truth, then greps the user-visible surfaces for any *other*
count that looks like a top-line tool reference. It also asks the runtime
for the actual MCP tool count and asserts runtime >= public count. Runtime
may be higher while post-manifest tools are held for the next intentional
public count bump.

Excluded surfaces:
- ``site/tos.html``, ``site/tokushoho.html``, ``site/privacy.html``,
  ``site/prompts.html`` (and the ``site/en/`` mirror): legal copy is
  reviewed separately.
- ``CHANGELOG.md`` and ``HANDOFF_*.md``: historical records.
- ``site/docs/search/search_index.json``: auto-regenerated by mkdocs.
- Files under ``site/programs/``: per-program text may legitimately list
  numeric figures unrelated to tool count (e.g. "23 tools available for
  manufacturing").

Usage:
    .venv/bin/python scripts/check_tool_count_consistency.py
    .venv/bin/python scripts/check_tool_count_consistency.py --fix-list

Exit codes:
    0  All references match the public manifest count and runtime has at least that many tools
    1  Drift detected (script prints offending file:line entries)
    2  Runtime introspection failed
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / "scripts" / "distribution_manifest.yml"

# User-visible roots that should track the canonical count.
INCLUDE_ROOTS = [
    REPO_ROOT / "site",
    REPO_ROOT / "docs",
    REPO_ROOT / "README.md",
    REPO_ROOT / "CLAUDE.md",
    REPO_ROOT / "pyproject.toml",
    REPO_ROOT / "server.json",
    REPO_ROOT / "mcp-server.json",
    REPO_ROOT / "dxt" / "manifest.json",
    REPO_ROOT / "smithery.yaml",
    REPO_ROOT / "scripts" / "distribution_manifest.yml",
    REPO_ROOT / "scripts" / "mcp_registries_submission.json",
    REPO_ROOT / "scripts" / "registry_submissions",
    REPO_ROOT / "src" / "jpintel_mcp" / "email" / "templates",
]

# Surfaces we deliberately do NOT verify.
EXCLUDE_PATH_FRAGMENTS = (
    "/tos.html",
    "/tokushoho.html",
    "/privacy.html",
    "/prompts.html",
    "/legal/",
    "CHANGELOG.md",  # historical
    "HANDOFF_",  # historical handoff snapshots
    "site/docs/search/search_index.json",  # auto-generated
    "site/programs/",  # per-program copy unrelated
    "site/_templates/",  # template skeleton, not user-visible
    "/_archive/",  # legacy
    "/_internal/",  # internal docs
    ".bak",
)

# Patterns that look like a top-line tool count statement.
TOOL_COUNT_PATTERNS = [
    re.compile(r"\b(\d{1,3}) MCP tools\b"),
    re.compile(r"\bMCP tools \((\d{1,3})\)\b"),
    re.compile(r"\b(\d{1,3}) tools at default gates\b"),
    re.compile(r"\b(\d{1,3}) at default gates\b"),
    re.compile(r"\b(\d{1,3}) at standard configuration\b"),
    re.compile(r"\b(\d{1,3}) tools \(protocol "),
    re.compile(r"\b(\d{1,3}) tools, protocol "),
    re.compile(r"\b(\d{1,3}) tool MCP\b"),
    re.compile(r"\b(\d{1,3})-tool MCP surface\b"),
    re.compile(r"\b(\d{1,3})-tool surface\b"),
    re.compile(r"\b(\d{1,3})\s*個の\s*MCP\s*ツール\b"),
    re.compile(r"\b(\d{1,3})\s*ツール\b"),
    re.compile(r"MCP\s*ツール総数[^0-9]{0,80}(\d{1,3})"),
    re.compile(r'data-fact=["\']mcp_tools_total["\'][^>]*>\s*(\d{1,3})'),
    re.compile(r'"tool_count_default_gates":\s*(\d{1,3})'),
    re.compile(r'"tool_count":\s*(\d{1,3})'),
]

# Numeric thresholds: any "<N> tools" within plausible MCP-count range is
# considered a candidate. Sub-counts like "7 tools" describing a
# subgroup are excluded by being out of this range; if you add a tool
# group with 25-50 tools, refine this further.
SUSPECT_RANGE = range(50, 201)


def public_manifest_tool_count() -> int:
    """Return the public MCP tool count pinned by distribution_manifest.yml."""
    text = MANIFEST_PATH.read_text(encoding="utf-8")
    match = re.search(r"^tool_count_default_gates:\s*(\d{1,3})\b", text, re.MULTILINE)
    if not match:
        sys.stderr.write(
            "[check_tool_count_consistency] tool_count_default_gates missing from "
            f"{MANIFEST_PATH.relative_to(REPO_ROOT)}\n"
        )
        sys.exit(2)
    return int(match.group(1))


def runtime_tool_count() -> int:
    """Return the actual tool count from the running MCP server."""
    venv_python = REPO_ROOT / ".venv" / "bin" / "python"
    if not venv_python.exists():
        venv_python = sys.executable
    cmd = [
        str(venv_python),
        "-c",
        (
            "import os; os.environ.setdefault('AUTONOMATH_ENABLED','1');"
            "os.environ.setdefault('AUTONOMATH_EXPERIMENTAL_MCP_ENABLED','1');"
            "os.environ.setdefault('AUTONOMATH_WAVE24_FIRST_HALF_ENABLED','1');"
            "os.environ.setdefault('AUTONOMATH_WAVE24_SECOND_HALF_ENABLED','1');"
            "os.environ.setdefault('AUTONOMATH_INTEL_COMPOSITE_ENABLED','1');"
            "os.environ.setdefault('AUTONOMATH_INTEL_WAVE32_ENABLED','1');"
            "from jpintel_mcp.mcp.server import mcp;"
            "print(len(mcp._tool_manager.list_tools()))"
        ),
    ]
    out = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    if out.returncode != 0:
        sys.stderr.write(
            f"[check_tool_count_consistency] runtime probe failed:\n"
            f"  stdout: {out.stdout}\n"
            f"  stderr: {out.stderr}\n"
        )
        sys.exit(2)
    # Last line is the count (other lines may carry log noise).
    for line in reversed(out.stdout.strip().splitlines()):
        line = line.strip()
        if line.isdigit():
            return int(line)
    sys.stderr.write(f"[check_tool_count_consistency] no integer in output:\n{out.stdout}\n")
    sys.exit(2)


def is_excluded(path: Path) -> bool:
    p = str(path)
    return any(frag in p for frag in EXCLUDE_PATH_FRAGMENTS)


def iter_files() -> list[Path]:
    out: list[Path] = []
    for root in INCLUDE_ROOTS:
        if root.is_file():
            if not is_excluded(root):
                out.append(root)
            continue
        if not root.exists():
            continue
        for p in root.rglob("*"):
            if not p.is_file():
                continue
            if p.suffix not in {".html", ".txt", ".md", ".json"}:
                continue
            if is_excluded(p):
                continue
            out.append(p)
    return out


def find_drift(canonical: int) -> list[tuple[Path, int, str, int]]:
    """Return list of (path, line_no, line_text, found_count) for drift."""
    hits: list[tuple[Path, int, str, int]] = []
    for fp in iter_files():
        try:
            text = fp.read_text(encoding="utf-8", errors="replace")
        except Exception:
            continue
        for line_no, line in enumerate(text.splitlines(), 1):
            for pat in TOOL_COUNT_PATTERNS:
                for m in pat.finditer(line):
                    found = int(m.group(1))
                    if found in SUSPECT_RANGE and found != canonical:
                        hits.append((fp, line_no, line.strip(), found))
    return hits


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--fix-list",
        action="store_true",
        help="Print only file:line:found_count, one per line (machine-friendly).",
    )
    parser.add_argument(
        "--canonical",
        type=int,
        default=None,
        help="Override the public manifest count (use with care).",
    )
    args = parser.parse_args()

    public_count = args.canonical if args.canonical is not None else public_manifest_tool_count()
    runtime_count = runtime_tool_count()

    if runtime_count < public_count:
        print(
            f"[check_tool_count_consistency] DRIFT — public manifest count is "
            f"{public_count} tools, but runtime exposes only {runtime_count} tools."
        )
        return 1

    drift = find_drift(public_count)

    if not drift:
        if not args.fix_list:
            print(
                f"[check_tool_count_consistency] OK — all references match public "
                f"manifest count ({public_count} tools); runtime exposes "
                f"{runtime_count} tools."
            )
        return 0

    if args.fix_list:
        for fp, line_no, _line, found in drift:
            print(f"{fp.relative_to(REPO_ROOT)}:{line_no}:{found}")
        return 1

    print(
        f"[check_tool_count_consistency] DRIFT — public manifest count = "
        f"{public_count} tools, runtime exposes {runtime_count} tools, but "
        f"found {len(drift)} occurrences of other counts in user-visible surfaces:"
    )
    for fp, line_no, line, found in drift:
        rel = fp.relative_to(REPO_ROOT)
        print(f"  {rel}:{line_no}  [{found} tools]  {line[:140]}")
    print()
    print(
        "Fix each line to use the canonical count. Excluded surfaces "
        "(legal copy, changelog history, auto-generated mkdocs index, "
        "per-program pages) are listed in this script's docstring."
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
