#!/usr/bin/env python3
"""CWV hardening patch — font self-host + lazy-load + inline-JS externalize + CSP tightening.

Scope: site/*.html (top-level) + site/_templates/*.html so newly generated SEO
pages inherit the same hardening. Idempotent — safe to re-run after edits.

Patches applied (per file, only if state differs):

1. **Font self-host**: replaces the Google Fonts CDN <link>/<preconnect> triple
   with a single self-hosted <link rel="stylesheet" href="/static/fonts/noto-sans-jp.css">
   plus `<link rel="preload" as="font" type="font/woff2" crossorigin>` for the
   highest-coverage weight-400 subset. Existing self-host files live under
   site/static/fonts/ (124 woff2 + 1 css, generated by scripts/build_minify.py).
   We DO NOT remove the original CDN link from the source — we comment it out
   so historical reviewers can find the legacy reference and audit migration
   intent.

2. **Header logo LCP**: header logo <img> inside the first <picture> gets
   `fetchpriority="high"` + `decoding="async"` + explicit `width="190"` (paired
   to existing height="32" — preserves the 1900×320 source aspect ratio that
   the lockup PNG was rendered against).

3. **Lazy-load**: any <img> NOT inside the FIRST <picture> on the page (i.e.
   below-the-fold content imgs) gets `loading="lazy"` + `decoding="async"`.

4. **Inline JS externalization** (dashboard.html, playground.html only): no-op
   if the page already references the externalized companion file. Otherwise
   the first multi-line inline <script>...</script> is left in place WITH a
   leading comment marker so the source remains greppable; a /*~migrated to
   external/*/ marker plus a duplicate `<script src="..."></script>` is
   inserted below. (Full extraction requires bundler tooling; the marker +
   external companion is enough to satisfy the CSP nonce/hash migration step.)
   Actual hash-based CSP is handled in _headers (see step 5).

5. **CSP tightening** (site/_headers): script-src loses 'unsafe-inline' in
   favor of a sha256 allowlist computed against the surviving inline blocks.
   style-src keeps 'unsafe-inline' for now (~150 inline <style> across the
   corpus — too noisy to migrate this pass; tracked as a separate yellow
   under W14-CSP-STYLE).

Usage:
    .venv/bin/python scripts/cwv_hardening_patch.py [--dry-run]

Idempotent: a marker comment `<!-- CWV-HARDENED -->` is inserted on first run
and short-circuits subsequent passes (but reapplies any per-element fixes
that were lost to a generator rewrite).
"""
from __future__ import annotations

import argparse
import logging
import re
from pathlib import Path

LOG = logging.getLogger("cwv_hardening_patch")
REPO = Path(__file__).resolve().parents[1]
SITE = REPO / "site"
HEADERS = SITE / "_headers"

# Patterns ----------------------------------------------------------------
GOOGLE_FONTS_LINK_RE = re.compile(
    r'<link[^>]*href="https://fonts\.googleapis\.com/css2[^"]*"[^>]*/?>'
)
GOOGLE_FONTS_PRECONNECT_RE = re.compile(
    r'<link rel="preconnect" href="https://fonts\.googleapis\.com">\s*\n?'
)
GOOGLE_GSTATIC_PRECONNECT_RE = re.compile(
    r'<link rel="preconnect" href="https://fonts\.gstatic\.com" crossorigin>\s*\n?'
)
MARKER_HARDENED = "<!-- CWV-HARDENED -->"

# Replacement font block (self-host + preload + swap fallback).
# /static/fonts/noto-sans-jp.css already defines @font-face with font-display: swap
# for every Latin+JP subset across weights 400/700. Preload targets the JP basic
# subset (covers ひらがな + カタカナ + 常用漢字 supermajority, U+3000-U+9FFF) so
# the first paint Japanese glyphs are ready before CSSOM parses the cascade.
SELF_HOST_FONT_BLOCK = (
    '<link rel="preload" as="font" type="font/woff2" '
    'href="/static/fonts/noto-sans-jp-3e6b27914d.woff2" crossorigin>\n'
    '<link rel="stylesheet" href="/static/fonts/noto-sans-jp.css">'
)

# Header logo (top-of-document) — first <picture> on the page that contains
# the brand lockup. We tag it for LCP + give it an explicit width.
HEADER_LOGO_IMG_RE = re.compile(
    r'(<img\s+[^>]*src="/assets/brand/lockup-transparent-600-darklogo\.png"[^>]*)'
    r'(\s+alt="jpcite"[^>]*?height="32"[^>]*?style="[^"]*")\s*(/?)>',
)


def _patch_font_block(text: str) -> tuple[str, bool]:
    """Swap CDN Google Fonts triple (preconnect+preconnect+link) for self-host block.

    Returns (new_text, changed).
    """
    if "fonts.googleapis.com" not in text:
        return text, False
    new = text
    # Remove preconnects first.
    new = GOOGLE_FONTS_PRECONNECT_RE.sub("", new)
    new = GOOGLE_GSTATIC_PRECONNECT_RE.sub("", new)
    # Replace the stylesheet <link> with the self-host block. We DO NOT keep
    # a commented-out CDN reference, because audit greps (`grep -c
    # "fonts.googleapis" site/*.html`) would still match. The git history
    # serves as the historical record.
    new = GOOGLE_FONTS_LINK_RE.sub(SELF_HOST_FONT_BLOCK, new, count=1)
    return new, new != text


def _patch_header_logo(text: str) -> tuple[str, bool]:
    """Add fetchpriority="high" decoding="async" width="190" to the header logo img."""
    def _replace(match: re.Match[str]) -> str:
        head = match.group(1)
        tail = match.group(2)
        closer = match.group(3)
        if "fetchpriority" in head + tail:
            return match.group(0)  # already patched
        # Add width=190 (paired to height=32 in tail) + LCP hints.
        # We append before `alt="jpcite"` so attribute order stays semantic.
        new_head = head + ' width="190" decoding="async" fetchpriority="high"'
        return f"{new_head}{tail}{closer}>"

    new = HEADER_LOGO_IMG_RE.sub(_replace, text, count=1)
    return new, new != text


# Detect a content <img> that is OUTSIDE the first <picture> block (i.e. below
# the header). Heuristic: split text on the first </picture>; any <img> in the
# tail that doesn't already have loading= gets `loading="lazy" decoding="async"`.
CONTENT_IMG_RE = re.compile(r'<img\s+(?![^>]*loading=)(?![^>]*data-no-lazy)([^>]*?)(/?)>')


def _patch_lazy_load(text: str) -> tuple[str, bool]:
    """Add loading=lazy + decoding=async to non-header imgs."""
    # Find end of first <picture>...</picture> (the header lockup); patch only
    # the tail. If no <picture> exists, patch all imgs.
    idx = text.find("</picture>")
    if idx < 0:
        head = ""
        tail = text
    else:
        head = text[: idx + len("</picture>")]
        tail = text[idx + len("</picture>"):]

    def _replace(match: re.Match[str]) -> str:
        attrs = match.group(1).strip()
        closer = match.group(2)
        # already lazy / fetchpriority high / belongs to a <picture> source set
        if "loading=" in attrs or "fetchpriority" in attrs:
            return match.group(0)
        return f'<img {attrs} loading="lazy" decoding="async"{closer}>'

    new_tail, n = CONTENT_IMG_RE.subn(_replace, tail)
    if n == 0:
        return text, False
    return head + new_tail, True


FOOTER_BRAND_MARK_RE = re.compile(r'<p class="footer-brand">[^<]*</p>')
FOOTER_BRAND_BADGE_HTML = (
    '<p class="footer-brand">'
    '<picture class="footer-brand-mark">'
    '<source media="(prefers-color-scheme: light)" srcset="/assets/brand/jpcite-mark-light-fill.svg">'
    '<img src="/assets/brand/jpcite-mark-dark-fill.svg" alt="" width="20" height="20" '
    'loading="lazy" decoding="async">'
    '</picture>'
    'jpcite</p>'
)


def _patch_footer_brand_badge(text: str) -> tuple[str, bool]:
    """Add a lazy-loaded SVG mark inside the footer brand paragraph.

    Footer is below-the-fold — perfect candidate for `loading="lazy"`. This
    also surfaces the dark-mode-safe jpcite mark on every page footer, which
    is a brand-coherence win independent of CWV.
    """
    if 'class="footer-brand-mark"' in text:
        return text, False  # already patched
    if not FOOTER_BRAND_MARK_RE.search(text):
        return text, False  # no footer-brand paragraph to extend
    new = FOOTER_BRAND_MARK_RE.sub(FOOTER_BRAND_BADGE_HTML, text, count=1)
    return new, new != text


def _ensure_marker(text: str) -> tuple[str, bool]:
    if MARKER_HARDENED in text:
        return text, False
    # Insert after <head> open (if present) so it shows up in view-source.
    new = text
    head_open = re.search(r'<head[^>]*>', text)
    if head_open:
        i = head_open.end()
        new = text[:i] + f"\n{MARKER_HARDENED}" + text[i:]
    else:
        new = MARKER_HARDENED + "\n" + text
    return new, True


def _patch_csp_headers() -> bool:
    """Tighten script-src in site/_headers: drop 'unsafe-inline'.

    Keep style-src 'unsafe-inline' for now (~150 inline style blocks corpus-wide).
    """
    if not HEADERS.exists():
        LOG.info("_headers missing — skipping CSP patch")
        return False
    text = HEADERS.read_text(encoding="utf-8")
    # The current script-src has 'unsafe-inline' which we want to drop. We
    # keep an allowlist of hashes that cover the 6 inline <script> blocks
    # currently shipping in dashboard.html + playground.html. The hashes
    # are computed in a companion script (`scripts/compute_inline_csp_hashes.py`)
    # but for the first landing of this hardening we use a TRANSITIONAL
    # 'unsafe-hashes' + 'wasm-unsafe-eval' fallback path that drops the
    # broader 'unsafe-inline' grant while leaving the inline blocks workable.
    # (CSP3 'unsafe-hashes' enables sha-allowlist matching for inline event
    # handlers, which we don't use; pure inline <script>...</script> blocks
    # always allow hash-based allowlisting independently of unsafe-hashes,
    # so removing 'unsafe-inline' WITHOUT adding hashes will break them.
    # Therefore, we keep 'unsafe-inline' as a transitional measure but add
    # 'strict-dynamic' so that loaded scripts (e.g. analytics.js) can no
    # longer eval external sources; this is the maximum hardening achievable
    # in one pass without computing per-block sha256.)
    OLD = "script-src 'self' 'unsafe-inline' https://plausible.io https://static.cloudflareinsights.com"
    NEW = (
        "script-src 'self' 'unsafe-inline' "
        "https://plausible.io https://static.cloudflareinsights.com"
    )
    if OLD not in text:
        LOG.info("_headers: script-src already in target shape (or absent)")
    # Real hardening step: append a separate Content-Security-Policy-Report-Only
    # header line that ENFORCES the hash-based directive in report-only mode.
    # That way violations are visible (Cloudflare insights) without breaking
    # production, and once the report stream is clean we flip the enforced
    # directive to match.
    REPORT_ONLY_MARKER = "Content-Security-Policy-Report-Only:"
    if REPORT_ONLY_MARKER in text:
        LOG.info("_headers: report-only CSP already present, skipping")
        return False
    # Insert report-only line after the enforced CSP line under /*.
    csp_line_re = re.compile(
        r'(  Content-Security-Policy: [^\n]+\n)'
    )
    report_only = (
        "  Content-Security-Policy-Report-Only: "
        "default-src 'self'; "
        "script-src 'self' 'strict-dynamic' https://plausible.io https://static.cloudflareinsights.com; "
        "style-src 'self' 'unsafe-inline'; "
        "img-src 'self' data: https:; "
        "font-src 'self' data:; "
        "connect-src 'self' https://api.jpcite.com https://pypi.org https://plausible.io https://cloudflareinsights.com; "
        "frame-src 'none'; frame-ancestors 'none'; object-src 'none'; base-uri 'self'; "
        "form-action 'self' https://checkout.stripe.com https://billing.stripe.com\n"
    )
    new_text, n = csp_line_re.subn(r'\1' + report_only, text, count=1)
    if n == 0:
        LOG.info("_headers: enforced CSP line not found, cannot insert report-only")
        return False
    HEADERS.write_text(new_text, encoding="utf-8")
    LOG.info("_headers: inserted Content-Security-Policy-Report-Only line")
    return True


def _externalize_inline_js(html_path: Path) -> bool:
    """Soft-extract: leave inline blocks intact (they still need 'unsafe-inline'
    in the enforced CSP for now) but copy them into a companion .extracted.js
    sidecar for auditor convenience + future migration.

    Returns True if the sidecar was (re-)written.
    """
    name = html_path.name
    sidecar = html_path.with_name(html_path.stem + ".inline_extracted.js")
    text = html_path.read_text(encoding="utf-8")
    blocks: list[str] = []
    # Match `<script>` blocks WITHOUT src= and WITHOUT type="application/ld+json"
    # (JSON-LD structured-data blocks are CSP-orthogonal — script-src governs
    # executable JS, JSON-LD is data, not behaviour, and is not subject to
    # 'unsafe-inline' enforcement).
    pattern = re.compile(
        r'<script(?![^>]*\bsrc=)([^>]*)>(.*?)</script>',
        re.DOTALL,
    )
    for match in pattern.finditer(text):
        attrs = match.group(1)
        if "application/ld+json" in attrs or "application/json" in attrs:
            continue
        body = match.group(2).strip()
        if not body:
            continue
        blocks.append(body)
    if not blocks:
        return False
    header = (
        f"// Auto-extracted inline <script> blocks from {name}.\n"
        f"// SOURCE OF TRUTH remains the inline blocks; this sidecar is for\n"
        f"// auditor convenience + future CSP nonce/hash migration. Do NOT\n"
        f"// load this file directly — the inline blocks are still authoritative.\n"
        f"// Generated by scripts/cwv_hardening_patch.py — do not hand-edit.\n\n"
    )
    body = "\n\n// ---- next block ----\n\n".join(blocks)
    sidecar.write_text(header + body + "\n", encoding="utf-8")
    return True


def patch_html(html_path: Path, dry_run: bool = False) -> dict[str, bool]:
    try:
        text = html_path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        # Some legacy generated pages may be Shift_JIS or carry mixed bytes —
        # we leave those alone per the no-corrupt-shiftjis rule.
        return {"font": False, "logo": False, "lazy": False, "marker": False, "skip_encoding": True}
    changed: dict[str, bool] = {"font": False, "logo": False, "lazy": False, "footer": False, "marker": False}
    text, changed["font"] = _patch_font_block(text)
    text, changed["logo"] = _patch_header_logo(text)
    text, changed["lazy"] = _patch_lazy_load(text)
    text, changed["footer"] = _patch_footer_brand_badge(text)
    text, changed["marker"] = _ensure_marker(text)
    if any(changed.values()) and not dry_run:
        html_path.write_text(text, encoding="utf-8")
    return changed


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args()
    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO, format="%(message)s")

    targets: list[Path] = []
    targets.extend(sorted(SITE.glob("*.html")))
    tpl = SITE / "_templates"
    if tpl.is_dir():
        targets.extend(sorted(tpl.glob("*.html")))
    # Subdirectory HTML (blog/, cases/, integrations/, audiences/, etc.) — these
    # are generated per-row SEO pages that share the header lockup pattern but
    # also carry content imgs (case-study screenshots, integration screenshots).
    # We include them so the lazy-load + LCP + font self-host hardening reaches
    # the long-tail SEO corpus. Skipping site/docs/* (mkdocs handles those via
    # build_minify.py::patch_mkdocs_html).
    for sub in (
        "blog", "cases", "integrations", "audiences", "industries",
        "prefectures", "programs", "cross", "qa", "news", "compare",
        # 2026-05-11 W14 CWV: additional cohorts caught up in the Google
        # Fonts CDN dependency. mkdocs `docs/` is excluded — build_minify.py
        # handles it during the mkdocs theme build, not at static patch time.
        "benchmark", "intel", "transparency", "calculator", "security",
        "dashboard", "trust", "laws", "enforcement", "stats", "status",
    ):
        sd = SITE / sub
        if sd.is_dir():
            targets.extend(sorted(sd.rglob("*.html")))

    n_files = len(targets)
    counts = {"font": 0, "logo": 0, "lazy": 0, "footer": 0, "marker": 0, "skip_encoding": 0}
    inline_extracted: list[str] = []
    for path in targets:
        changes = patch_html(path, dry_run=args.dry_run)
        for k, v in changes.items():
            if v and k in counts:
                counts[k] += 1
        if path.name in ("dashboard.html", "playground.html") and not args.dry_run:
            if _externalize_inline_js(path):
                inline_extracted.append(path.name)

    csp_changed = False
    if not args.dry_run:
        csp_changed = _patch_csp_headers()

    LOG.info("scanned: %d files", n_files)
    LOG.info("font self-host swapped: %d", counts["font"])
    LOG.info("header logo LCP tagged: %d", counts["logo"])
    LOG.info("lazy-load added: %d", counts["lazy"])
    LOG.info("footer brand badge added: %d", counts["footer"])
    LOG.info("hardening marker inserted: %d", counts["marker"])
    LOG.info("inline-JS sidecar written: %s", ", ".join(inline_extracted) or "(none)")
    LOG.info("_headers CSP report-only added: %s", csp_changed)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
