#!/usr/bin/env python3
"""Generate ``site/sitemap-companion-md.xml`` from current HTML inventory.

Wave 17 AX — companion-Markdown discovery surface.

Enumerates every SEO HTML page in ``site/cases``, ``site/laws``, and
``site/enforcement`` and emits a ``<url>`` entry pointing at the
GitHub-style ``.md`` companion (``https://jpcite.com/{cat}/{slug}.md``).

The script is idempotent: it always overwrites the output file and is
safe to run on every chunk push. ``lastmod`` is the current UTC date.

Usage
-----
    python scripts/generate_sitemap_companion_md.py
    python scripts/generate_sitemap_companion_md.py --require-md-exists
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SITE_DIR = REPO_ROOT / "site"
OUTPUT_PATH = SITE_DIR / "sitemap-companion-md.xml"
CANONICAL_BASE = "https://jpcite.com"

CATEGORIES: tuple[tuple[str, str], ...] = (
    ("cases", "cases"),
    ("laws", "laws"),
    ("enforcement", "enforcement"),
)


def _today_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _enumerate_md_urls(require_md_exists: bool) -> list[tuple[str, str]]:
    """Return (category, md_url) tuples for every .html page in scope."""
    entries: list[tuple[str, str]] = []
    for cat, dir_name in CATEGORIES:
        cat_dir = SITE_DIR / dir_name
        if not cat_dir.is_dir():
            continue
        for p in sorted(cat_dir.iterdir()):
            if not p.is_file() or p.suffix != ".html" or p.name == "index.html":
                continue
            slug = p.stem
            md_url = f"{CANONICAL_BASE}/{dir_name}/{slug}.md"
            if require_md_exists:
                md_path = p.with_suffix(".md")
                if not md_path.exists():
                    continue
            entries.append((cat, md_url))
    return entries


def _render_sitemap(entries: list[tuple[str, str]], lastmod: str) -> str:
    head = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<!--\n"
        "  Companion-Markdown surface sitemap for jpcite.com.\n"
        "  Generated by scripts/generate_sitemap_companion_md.py — do not edit by hand.\n"
        "\n"
        "  Each <loc> points at the GitHub-style `{url}.md` companion next to\n"
        "  a public-record SEO HTML page (cases / laws / enforcement). LLM\n"
        "  citation crawlers and AEO agents can ingest the .md surface\n"
        "  directly without JS-aware HTML parsing.\n"
        "-->\n"
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    )
    body_parts: list[str] = []
    for _cat, url in entries:
        body_parts.append(
            "  <url>\n"
            f"    <loc>{url}</loc>\n"
            f"    <lastmod>{lastmod}</lastmod>\n"
            "    <changefreq>monthly</changefreq>\n"
            "    <priority>0.5</priority>\n"
            "  </url>\n"
        )
    tail = "</urlset>\n"
    return head + "".join(body_parts) + tail


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--require-md-exists",
        action="store_true",
        help="Only include URLs whose .md sibling already exists on disk.",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Print stats but do not write the sitemap.",
    )
    args = p.parse_args(argv)
    entries = _enumerate_md_urls(args.require_md_exists)
    if not entries:
        sys.stderr.write("[sitemap-companion-md] no .md URLs to emit\n")
        return 2
    lastmod = _today_iso()
    body = _render_sitemap(entries, lastmod)
    if not args.dry_run:
        OUTPUT_PATH.write_text(body, encoding="utf-8")
    by_cat: dict[str, int] = {}
    for cat, _ in entries:
        by_cat[cat] = by_cat.get(cat, 0) + 1
    print(
        f"[sitemap-companion-md] {'DRY ' if args.dry_run else ''}wrote "
        f"{OUTPUT_PATH.relative_to(REPO_ROOT)} ({len(entries)} URLs, "
        f"{len(body)} bytes, lastmod={lastmod})"
    )
    for cat in sorted(by_cat):
        print(f"  {cat:>11}: {by_cat[cat]} URLs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
