#!/usr/bin/env python3
"""Rebrand notice: one-shot bulk send to every newsletter / launch-update
subscriber telling them that **AutonoMath / 税務会計AI / zeimu-kaikei.ai**
is now **jpcite** and their existing access keeps working unchanged.

Memory anchors (do NOT regress):
    * project_jpcite_rename — 2026-04-30 brand rename, 6-month redirect
      window, no commercial / legal restructure.
    * feedback_no_operator_llm_api — operator-side scripts MUST NOT
      import any LLM SDK (anthropic / openai / google.generativeai /
      claude_agent_sdk). This script wraps a pre-existing Postmark
      template; the body copy lives in Postmark UI, NOT generated by an
      LLM here.
    * feedback_zero_touch_solo — no `--reply-to` person, no operator
      phone / Slack escalation. The mail's reply-to is the standard
      info@bookyou.net mailbox handled by the operator.

What this script does NOT do:
    * Generate body text via an LLM (forbidden — see memory above).
      The Postmark template alias 'rebrand-notice-2026-04-30' is
      hand-written in the Postmark UI and ships its own HTML +
      plaintext.
    * Touch the `compliance_subscribers` (paid law-amendment alert)
      list — those subscribers got a separate transactional notice via
      `regenerate_audit_log_rss.py` per the rebrand calendar.
    * Re-send to anyone who has unsubscribed (subscribers row carries
      `unsubscribed_at`; we filter them out at SQL level).

Usage:
    python scripts/notify_existing_users.py --dry-run            # plan only, no sends
    python scripts/notify_existing_users.py --limit 50 --dry-run # smoke-test on 50
    python scripts/notify_existing_users.py                      # real send (one-shot)
    python scripts/notify_existing_users.py --since 2026-04-01   # filter by signup date

Idempotency:
    A successful send appends one row per recipient to
    analytics/rebrand_notify_log.jsonl. On re-invocation, recipients
    already present in that log are skipped — so an interrupted run is
    safe to resume. To force re-send (e.g. if the template was botched),
    delete the log file or pass `--force`.

Operator workflow:
    1. Verify the Postmark template 'rebrand-notice-2026-04-30' exists
       and previews correctly (from / subject / body).
    2. Run `--dry-run --limit 5` and read the log line — confirm the
       address sample looks right.
    3. Run `--limit 5` (real) and check the recipient inboxes.
    4. Run unbounded (no `--limit`) for the full sweep.
    5. Append the sweep timestamp to docs/launch_announcement_calendar.md
       under the 'rebrand 一括通知' row.
"""

from __future__ import annotations

import argparse
import contextlib
import json
import logging
import os
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Path bootstrap. Same pattern as the other scripts/cron/*.py — we want to
# run this from anywhere (`python scripts/notify_existing_users.py`) and
# have the in-repo `src/jpintel_mcp/` import work without a `pip install -e .`.
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)
logger = logging.getLogger("rebrand_notify")

LOG_PATH = REPO_ROOT / "analytics" / "rebrand_notify_log.jsonl"
DB_PATH_ENV = "JPINTEL_DB_PATH"
DB_PATH_DEFAULT = REPO_ROOT / "data" / "jpintel.db"

# Postmark template alias — pre-created in the Postmark UI by the
# operator. Body / subject live there, NOT here. Template variables
# expected: {brand_old, brand_new, info_url, unsub_url, year}.
TEMPLATE_ALIAS = "rebrand-notice-2026-04-30"
INFO_URL = "https://jpcite.com/about.html#rebrand-2026-04-30"
TAG = "rebrand-notice"


# ---------------------------------------------------------------------------
# DB layer
# ---------------------------------------------------------------------------


def _open_db(path: Path) -> sqlite3.Connection:
    """Open jpintel.db read-only for the SELECT (we never write back here —
    the unsubscribe channel writes through `api/subscribers.py`)."""
    if not path.exists():
        raise SystemExit(f"DB not found: {path} (set JPINTEL_DB_PATH or pass --db)")
    uri = f"file:{path}?mode=ro"
    conn = sqlite3.connect(uri, uri=True)
    conn.row_factory = sqlite3.Row
    return conn


def _select_recipients(
    conn: sqlite3.Connection,
    *,
    since: str | None,
    limit: int | None,
) -> list[sqlite3.Row]:
    """Pick every active newsletter subscriber. `since` filters by
    `created_at` (ISO-8601 prefix; trailing time portion ignored).

    We deliberately do NOT join `compliance_subscribers` (paid alert
    list) — those got their own notice path. Mixing the lists here
    would risk a paid customer getting two near-identical mails.
    """
    sql = """
        SELECT email, source, created_at
        FROM subscribers
        WHERE unsubscribed_at IS NULL
          AND email IS NOT NULL
          AND email <> ''
    """
    params: list[Any] = []
    if since:
        sql += " AND created_at >= ?"
        params.append(since)
    sql += " ORDER BY created_at ASC"
    if limit:
        sql += " LIMIT ?"
        params.append(limit)
    return list(conn.execute(sql, params))


# ---------------------------------------------------------------------------
# Idempotency log
# ---------------------------------------------------------------------------


def _load_already_sent() -> set[str]:
    """Return the set of email addresses already covered by a previous run.

    Format of each line: {"email": str, "ts": str, "status": str, ...}.
    Malformed lines are tolerated (logged + skipped) so a corrupt tail
    never blocks the re-run.
    """
    if not LOG_PATH.exists():
        return set()
    sent: set[str] = set()
    with LOG_PATH.open("r", encoding="utf-8") as fp:
        for raw in fp:
            raw = raw.strip()
            if not raw:
                continue
            try:
                row = json.loads(raw)
            except json.JSONDecodeError:
                logger.warning("rebrand_notify.log.malformed line=%r", raw[:120])
                continue
            email = row.get("email")
            status = row.get("status")
            if email and status in {"sent", "skipped_in_test_mode"}:
                sent.add(email.lower())
    return sent


def _append_log(row: dict[str, Any]) -> None:
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    with LOG_PATH.open("a", encoding="utf-8") as fp:
        fp.write(json.dumps(row, ensure_ascii=False) + "\n")


# ---------------------------------------------------------------------------
# Send
# ---------------------------------------------------------------------------


def _build_template_model(email: str, source: str | None) -> dict[str, Any]:
    """Variables the Postmark template will substitute. Keep this LEAN —
    the full body is in Postmark, not here.

    `unsub_url` is built from the same HMAC-token helper that powers the
    weekly digest, so the rebrand mail's footer link is interchangeable
    with every other broadcast mail."""
    # Local import keeps the bootstrap path lazy — script still runs in
    # `--dry-run` even if jpintel_mcp is not on sys.path.
    from jpintel_mcp.api.subscribers import make_unsubscribe_token

    token = make_unsubscribe_token(email)
    return {
        "email": email,
        "source": source or "newsletter",
        "brand_old": "AutonoMath / 税務会計AI / zeimu-kaikei.ai",
        "brand_new": "jpcite",
        "info_url": INFO_URL,
        "unsub_url": f"https://jpcite.com/v1/subscribers/unsubscribe?token={token}",
        "year": datetime.now(timezone.utc).year,
    }


def _send_one(
    *,
    to: str,
    template_model: dict[str, Any],
    dry_run: bool,
) -> dict[str, Any]:
    """Hand off to the existing PostmarkClient — same path the welcome /
    digest / dunning mails use. NEVER instantiates a new HTTP client; the
    module-level singleton in `jpintel_mcp.email.postmark` reuses one
    httpx connection pool across the whole sweep."""
    if dry_run:
        logger.info(
            "rebrand_notify.dry_run to=%s template=%s vars=%s",
            to,
            TEMPLATE_ALIAS,
            sorted(template_model.keys()),
        )
        return {"skipped": True, "reason": "dry_run"}

    try:
        # Local import so `--help` and `--dry-run` work without a
        # configured Postmark token.
        from jpintel_mcp.email import get_client
    except ImportError as exc:
        logger.error("rebrand_notify.email_module_unavailable err=%s", exc)
        return {"error": "email_module_unavailable", "detail": str(exc)}

    try:
        client = get_client()
        # We use the BROADCAST stream because this is a list-wide
        # notification, NOT a transactional reply to a customer-initiated
        # action. Postmark splits reputation between the two streams; a
        # bulk rebrand mail going through `outbound` would torch our
        # transactional-stream IP score for weeks.
        from jpintel_mcp.email.postmark import STREAM_BROADCAST

        return client._send(  # type: ignore[attr-defined]
            to=to,
            template_alias=TEMPLATE_ALIAS,
            template_model=template_model,
            message_stream=STREAM_BROADCAST,
            tag=TAG,
        )
    except Exception as exc:  # pragma: no cover — defensive
        logger.warning("rebrand_notify.send_failed to=%s err=%s", to, exc)
        return {"error": "send_failed", "detail": str(exc)}


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def run(
    *,
    db_path: Path,
    since: str | None,
    limit: int | None,
    dry_run: bool,
    force: bool,
) -> dict[str, Any]:
    """Top-level. Returns a summary dict so the caller (CI / repl) can
    assert without re-parsing logs."""
    already = set() if force else _load_already_sent()
    if already:
        logger.info(
            "rebrand_notify.resume previously_sent=%d log=%s",
            len(already),
            LOG_PATH,
        )

    summary = {
        "candidates": 0,
        "skipped_already_sent": 0,
        "sent": 0,
        "errors": 0,
        "dry_run": dry_run,
    }

    with contextlib.closing(_open_db(db_path)) as conn:
        recipients = _select_recipients(conn, since=since, limit=limit)

    summary["candidates"] = len(recipients)
    logger.info("rebrand_notify.candidates n=%d since=%s limit=%s", len(recipients), since, limit)

    for row in recipients:
        email = row["email"].strip()
        if not email:
            continue
        if email.lower() in already:
            summary["skipped_already_sent"] += 1
            continue

        template_model = _build_template_model(email, row["source"])
        result = _send_one(to=email, template_model=template_model, dry_run=dry_run)

        ts = datetime.now(timezone.utc).isoformat(timespec="seconds")
        if dry_run:
            status = "dry_run"
        elif result.get("error"):
            status = "error"
            summary["errors"] += 1
        elif result.get("skipped"):
            # Postmark client returns {skipped: True} when test_mode is on
            # (no API token). We log that as success-equivalent so a
            # follow-up real run doesn't double-send.
            status = "skipped_in_test_mode"
            summary["sent"] += 1
        else:
            status = "sent"
            summary["sent"] += 1

        _append_log(
            {
                "ts": ts,
                "email": email,
                "source": row["source"],
                "template": TEMPLATE_ALIAS,
                "status": status,
                "result_shape": sorted((result or {}).keys()),
            }
        )

    logger.info("rebrand_notify.summary %s", json.dumps(summary, ensure_ascii=False))
    return summary


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    p.add_argument(
        "--db",
        type=Path,
        default=Path(os.environ.get(DB_PATH_ENV, DB_PATH_DEFAULT)),
        help=f"Path to jpintel.db (default: ${DB_PATH_ENV} or {DB_PATH_DEFAULT})",
    )
    p.add_argument(
        "--since",
        type=str,
        default=None,
        help="Only notify subscribers created on or after this ISO date "
        "(e.g. 2026-04-01). Default: notify all.",
    )
    p.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Cap the number of recipients (smoke-testing).",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Do not call Postmark; log what would be sent.",
    )
    p.add_argument(
        "--force",
        action="store_true",
        help="Ignore the rebrand_notify_log.jsonl idempotency log "
        "(re-send to addresses already covered).",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    summary = run(
        db_path=args.db,
        since=args.since,
        limit=args.limit,
        dry_run=args.dry_run,
        force=args.force,
    )
    # Exit code 0 even on partial errors — the GitHub Action workflow_dispatch
    # caller reads the summary line out of the log to decide follow-up.
    # Non-zero only for catastrophic configuration failure (DB missing,
    # which is raised earlier as SystemExit).
    if summary["errors"] and not args.dry_run:
        logger.warning("rebrand_notify.completed_with_errors n=%d", summary["errors"])
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
