#!/usr/bin/env python3
"""Assemble the master sitemap-index.xml for jpcite.com.

The site has multiple sitemaps:
- sitemap.xml (hand-maintained static URLs: home, /docs, /pricing, etc.)
- sitemap-programs.xml (per-program HTML, auto-generated)
- sitemap-prefectures.xml / sitemap-cross*.xml / sitemap-industries*.xml
  / sitemap-cities.xml (GEO pages)
- sitemap-audiences.xml / sitemap-qa.xml / sitemap-pages.xml (content pages)
- sitemap-enforcement.xml (administrative action detail pages)
- docs/sitemap.xml (MkDocs output)

NOTE: site/structured/*.jsonld shards were retired 2026-05-03. JSON-LD is now
inlined in every /programs/<slug>.html page (one <script
type="application/ld+json"> per page), keeping the CF Pages deploy under the
20k-file limit. sitemap-structured.xml remains as the public discovery shard
for pages carrying inline JSON-LD.

When sitemap-programs has > 50,000 URLs (sitemap.org spec) the program
generator splits into shards `sitemap-programs-1.xml`, `sitemap-programs-2.xml`
etc. We don't expect that yet (~11k rows) but the discovery code below
handles it transparently.

This script writes site/sitemap-index.xml which is the file submitted to
Google Search Console / Bing Webmaster Tools.

Usage
-----
    .venv/bin/python scripts/sitemap_gen.py [--domain jpcite.com]

It is idempotent — if the new content matches the existing file the file is
left untouched (so git diffs are clean).
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
from datetime import date
from pathlib import Path
from xml.sax.saxutils import escape

LOG = logging.getLogger("sitemap_gen")

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SITE_DIR = REPO_ROOT / "site"
DEFAULT_DOMAIN = "jpcite.com"

# Sitemaps that, if present, should be referenced in the master index.
# Order: hand-maintained core first, then auto-generated bulk.
KNOWN_BASENAMES = (
    "sitemap.xml",
    "sitemap-programs.xml",  # may itself be a sitemapindex if sharded
    "sitemap-audiences.xml",
    "sitemap-prefectures.xml",
    "sitemap-cross.xml",
    "sitemap-cross-detail.xml",
    "sitemap-industries.xml",
    "sitemap-industries-detail.xml",
    "sitemap-pages.xml",
    "sitemap-qa.xml",
    "sitemap-enforcement.xml",
    "sitemap-cities.xml",
    # Wave 18 B6: GEO substrate (facts_registry JSON light + full) surfaced
    # as a sitemap shard so AI bots discover the registry without scraping
    # 24k+ per-entity HTML pages.
    "sitemap-facts.xml",
    # Wave 17 AX: cases / laws / enforcement HTML surfaces (~5k pages combined).
    "sitemap-cases.xml",
    "sitemap-enforcement-cases.xml",
    "sitemap-laws.xml",
    "sitemap-laws-en.xml",
    # Wave 22 correction (2026-05-11): companion-Markdown surface sitemap.
    # Generated by scripts/generate_sitemap_companion_md.py --scan-md-only from
    # the on-disk public .md inventory, including root/press/legal/security
    # companions added later.
    "sitemap-companion-md.xml",
    "sitemap-llms.xml",
    "sitemap-structured.xml",
    "docs/sitemap.xml",
)

# Glob for sharded sitemap-programs files (numbered shards, e.g. sitemap-programs-1.xml).
SHARD_PATTERNS = ("sitemap-programs-*.xml",)


def _file_lastmod_iso(path: Path) -> str:
    """Return YYYY-MM-DD lastmod derived from file mtime, or today if missing."""
    try:
        ts = path.stat().st_mtime
    except OSError:
        return date.today().isoformat()
    return date.fromtimestamp(ts).isoformat()


def discover_sitemaps(site_dir: Path) -> list[tuple[str, str]]:
    """Return [(basename, lastmod_iso), ...] for every sitemap to reference."""
    out: list[tuple[str, str]] = []
    seen: set[str] = set()
    for name in KNOWN_BASENAMES:
        p = site_dir / name
        if p.exists() and p.is_file():
            out.append((name, _file_lastmod_iso(p)))
            seen.add(name)
    for pattern in SHARD_PATTERNS:
        for p in sorted(site_dir.glob(pattern)):
            name = p.name
            if name in seen:
                continue
            out.append((name, _file_lastmod_iso(p)))
            seen.add(name)
    return out


def build_index(entries: list[tuple[str, str]], domain: str) -> str:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!--",
        "  Master sitemap index for jpcite.com.",
        "  Submit this URL to Google Search Console / Bing Webmaster Tools.",
        "  Maintained for public crawler discovery.",
        "-->",
        '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    for name, lastmod in entries:
        lines.append("  <sitemap>")
        lines.append(f"    <loc>https://{escape(domain)}/{escape(name)}</loc>")
        lines.append(f"    <lastmod>{lastmod}</lastmod>")
        lines.append("  </sitemap>")
    lines.append("</sitemapindex>")
    return "\n".join(lines) + "\n"


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists():
        try:
            existing = path.read_text(encoding="utf-8")
        except OSError:
            existing = None
        if existing == content:
            return False
    path.write_text(content, encoding="utf-8")
    return True


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--site-dir",
        type=Path,
        default=DEFAULT_SITE_DIR,
        help="path to site/ (default: %(default)s)",
    )
    p.add_argument(
        "--domain",
        default=os.environ.get("JPINTEL_DOMAIN", DEFAULT_DOMAIN),
        help=f"public domain (default: {DEFAULT_DOMAIN})",
    )
    p.add_argument(
        "--out",
        type=Path,
        default=None,
        help="output path; default <site-dir>/sitemap-index.xml",
    )
    p.add_argument("--verbose", "-v", action="store_true")
    return p.parse_args()


def main() -> int:
    args = _parse_args()
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )
    site_dir: Path = args.site_dir
    out_path: Path = args.out or (site_dir / "sitemap-index.xml")

    if not site_dir.exists():
        LOG.error("site dir not found: %s", site_dir)
        return 1

    entries = discover_sitemaps(site_dir)
    if not entries:
        LOG.warning("no sitemap files discovered under %s", site_dir)
        return 1

    body = build_index(entries, args.domain)
    changed = write_if_changed(out_path, body)
    if changed:
        LOG.info("wrote %s with %d sitemaps", out_path, len(entries))
    else:
        LOG.info("%s unchanged (%d sitemaps)", out_path, len(entries))
    return 0


if __name__ == "__main__":
    sys.exit(main())
